yt-dlp: vgreb: implement persistent history and filename tracking

diff --git a/yt-dlp/.local/bin/vgreb b/yt-dlp/.local/bin/vgreb
--- a/yt-dlp/.local/bin/vgreb
+++ b/yt-dlp/.local/bin/vgreb
@@ -23,23 +23,44 @@ if [[ "$url" =~ [[:space:]] ]]; then
     exit 1
 fi
 
-safe_url=$(echo -n "$url" | sed 's/[^a-zA-Z0-9]/_/g' | cut -c 1-100)
+prefix="$HOME/.$self"
+history="$prefix/history"
+log_dir="$prefix/logs"
 
-log_dir="/tmp/${self}_$(whoami)"
+mkdir -p "$prefix"
 mkdir -p "$log_dir"
-log_file="$log_dir/$safe_url.log"
+SHA=sha1sum
+url_hash="$(echo -n $url | $SHA | awk '{print $1}')"
+log_file="$log_dir/${url_hash}.log"
+
+log_format='%s\t%s\t%s\t%\t%ss\n'
+[ ! -f "$history" ] && printf "$log_format" date state url file log_file > "$history"
+
+history_line() {
+    # $1: SUCCESS|FAIL
+    # $2: actual downloaded file
+    printf "$log_format" "$(date -Iseconds)" "$1" "$url" "$2" "$log_file"
+}
 
 msg "Download start: $url"
+tmpfile=$(mktemp)
+export VGREB_TMPFILE="$tmpfile"
 yt-dlp --color never --no-progress \
+    --download-archive "$prefix/archive.txt" \
     --rm-cache-dir \
+    --exec 'after_move:echo '{}' > "$VGREB_TMPFILE"' \
     "$url" > "$log_file" 2>&1
 rc=$?
+downloaded_file="$(cat $tmpfile)"
+rm -f -- $tmpfile
 
 if [ $rc -eq 0 ]; then
+    history_line SUCCESS "$downloaded_file" >> "$history"
     msg "Complete: $url"
 else
-    echo "Fail: $url (exit with $rc). See $log_file"
-    echo "$url" $(date -Iseconds) "$log_file" >> "$log_dir/error_urls"
+    history_line FAIL "$downloaded_file" >> "$history"
+    echo "Fail: $url (exit with $rc)."
+    cat "$log_file" >&2
     action=$(notify-send "$self" "Fail: $rc. Click to see log" \
         --action="default=View Log")
 
