yt-dlp: vgreb: refactor download logic into cmd_download

diff --git a/yt-dlp/.local/bin/vgreb b/yt-dlp/.local/bin/vgreb
--- a/yt-dlp/.local/bin/vgreb
+++ b/yt-dlp/.local/bin/vgreb
@@ -1,31 +1,14 @@
 #!/usr/bin/env bash
 
-url="$(tee | xargs)"
 self=vgreb
-
-if [ -t 0 ] && [ $# -eq 0 ]; then
-    echo "Usage: echo <url> | $self"
-    exit 1
-fi
 
 msg() {
     notify-send "$self" "$1"
     echo "$self: $1"
 }
 
-if [ -z "$url" ]; then
-    msg "Error: no url provided" >&2
-    exit 1
-fi
-
-if [[ "$url" =~ [[:space:]] ]]; then
-    msg "Error: $url: Invalid URL (whitespace detected)" >&2
-    exit 1
-fi
-
 prefix="$HOME/.$self"
 history="$prefix/history"
-download_id=$(uuidgen | tr -d '-')
 log_dir="$prefix/logs"
 log_file="$log_dir/${download_id}.log"
 format='%s\t%s\t%s\t%s\t%s\t%s\n'
@@ -48,47 +31,68 @@ ts() {
     date -Iseconds
 }
 
-# start download
-start_ts=$(ts)
-na="N/A"
-histlock bash -c 'printf "$1" "$2" "$3" "$4" "$5" "$6" "$7" >> "$8"' -- \
-         "$format" "$download_id" "$start_ts" "$na" "DOWNLOADING" "$url" "$na" "$history"
+cmd_download() {
+    url="$1"
 
-msg "Download start: $url"
+    if [ -t 0 ] && [ $# -eq 0 ]; then
+        echo "Usage: echo <url> | $self"
+        exit 1
+    fi
 
-tmpfile=$(mktemp)
-export VGREB_TMPFILE="$tmpfile"
-yt-dlp --color never --progress --newline \
-    --download-archive "$prefix/archive.txt" \
-    --rm-cache-dir \
-    --exec 'after_move:echo "{}" > "$VGREB_TMPFILE"' \
-    "$url" > "$log_file" 2>&1
-rc=$?
-end_ts=$(ts)
+    if [ -z "$url" ]; then
+        msg "Error: no url provided" >&2
+        exit 1
+    fi
 
-if [ -s "$tmpfile" ]; then
-    dfile="$(cat "$tmpfile")"
-else
-    dfile="$na"
-fi
-rm -f -- $tmpfile
+    if [[ "$url" =~ [[:space:]] ]]; then
+        msg "Error: $url: Invalid URL (whitespace detected)" >&2
+        exit 1
+    fi
 
-if [ $rc -eq 0 ]; then
-    [ "$dfile" = "$na" ] && state="EXIST" || state="SUCCESS"
-    msg "Complete: ${dfile##*/}"
-else
-    state="FAIL($rc)"
-    echo "Fail: $url (exit with $rc)."
-    cat "$log_file" >&2
-    action=$(notify-send "$self" "Fail: $rc. Click to see log" \
-                         --action="default=View Log")
-    case "$action" in
-        "default") foot -T "${self}-log" less "$log_file" ;;
-    esac
-fi
+    download_id=$(uuidgen | tr -d '-')
+    start_ts=$(ts)
+    na="N/A"
+    histlock bash -c 'printf "$1" "$2" "$3" "$4" "$5" "$6" "$7" >> "$8"' -- \
+             "$format" "$download_id" "$start_ts" "$na" "DOWNLOADING" "$url" "$na" "$history"
 
-new_line="$(printf "$format" "$download_id" "$start_ts" "$end_ts" \
-                   "$state" "$url" "$dfile")"
-histlock sed -i "s|^.*$download_id.*$|$new_line|" "$history"
+    msg "Download start: $url"
 
-exit $rc
+    tmpfile=$(mktemp)
+    export VGREB_TMPFILE="$tmpfile"
+    yt-dlp --color never --progress --newline \
+           --download-archive "$prefix/archive.txt" \
+           --rm-cache-dir \
+           --exec 'after_move:echo "{}" > "$VGREB_TMPFILE"' \
+           "$url" > "$log_file" 2>&1
+    rc=$?
+    end_ts=$(ts)
+
+    if [ -s "$tmpfile" ]; then
+        dfile="$(cat "$tmpfile")"
+    else
+        dfile="$na"
+    fi
+    rm -f -- $tmpfile
+
+    if [ $rc -eq 0 ]; then
+        [ "$dfile" = "$na" ] && state="EXIST" || state="SUCCESS"
+        msg "Complete: ${dfile##*/}"
+    else
+        state="FAIL($rc)"
+        echo "Fail: $url (exit with $rc)."
+        cat "$log_file" >&2
+        action=$(notify-send "$self" "Fail: $rc. Click to see log" \
+                             --action="default=View Log")
+        case "$action" in
+            "default") foot -T "${self}-log" less "$log_file" ;;
+        esac
+    fi
+
+    new_line="$(printf "$format" "$download_id" "$start_ts" "$end_ts" \
+                       "$state" "$url" "$dfile")"
+    histlock sed -i "s|^.*$download_id.*$|$new_line|" "$history"
+
+    exit $rc
+}
+
+cmd_download "$(tee | xargs)"
